services:
  megaqueue:
    image: rabbitmq:3.12-management
    container_name: megaqueue
    hostname: megaqueue
    
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    
    env_file:
    - .env

    volumes:
      - megaqueue_data:/var/lib/rabbitmq
      - ./config:/etc/rabbitmq
    
    networks:
      - megagera_network
    
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  megaqueue_data:
    driver: local

networks:
  megagera_network:
    external: true
